version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: smart_ghar_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data